
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.figures.lexerandparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int SQUARE = 4;
  public static final int PLUS = 16;
  public static final int RPAREN = 15;
  public static final int CURVE = 11;
  public static final int CIRCLE = 3;
  public static final int ERROR = 20;
  public static final int COLOR = 12;
  public static final int LPAREN = 14;
  public static final int RCTNGL = 5;
  public static final int POLYGN = 7;
  public static final int COMMA = 13;
  public static final int ANIMT = 8;
  public static final int EOF = 0;
  public static final int OBJ = 9;
  public static final int DIV = 19;
  public static final int GRAPH = 2;
  public static final int MINUS = 17;
  public static final int error = 1;
  public static final int ANT = 10;
  public static final int LINE = 6;
  public static final int ENTERO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAPH",
  "CIRCLE",
  "SQUARE",
  "RCTNGL",
  "LINE",
  "POLYGN",
  "ANIMT",
  "OBJ",
  "ANT",
  "CURVE",
  "COLOR",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "ERROR",
  "ENTERO"
  };
}

